name: Deploy Prod

on:
  push:
    branches:
      - prod
      - dev


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Deplay to GitHub Pages 
        uses: peaceiris/actions-gh-pages@v3 
        with:
          publish_dir: ./
          destination_dir: ${{ github.ref_name == 'prod' || ' ' || 'dev' }}
